# =============================================
# Configurações da Aplicação
# =============================================
spring.application.name=financeiro-api

# =============================================
# Banco de Dados - PostgreSQL
# =============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/financeiro_db
spring.datasource.username=postgres
spring.datasource.password=eliz95
spring.datasource.driver-class-name=org.postgresql.Driver

# =============================================
# JPA / Hibernate
# =============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =============================================
# JWT
# =============================================
jwt.secret=3f8b2c1d9e7a4f6b0c5d8e2a1b3c7f9d4e6a8b0c2d5f7a9b1c3e5f7a9b2d4f6a
jwt.expiration=86400000

# =============================================
# Swagger
# =============================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# =============================================
# Server
# =============================================
server.port=8080
